### PR TITLE
chore: fix issue templates

### PR DESCRIPTION
**Pull request by dmccaffery**
* replace checkboxes with multi-dropdowns
* add placeholders for most things

### CODE REVIEW

**Comment by dmccaffery** [comment]
@sjk07 : to preview the issue templates:

https://github.com/dmccaffery/numonic/blob/fix/issues/.github/ISSUE_TEMPLATE/bug-report.yml

and

https://github.com/dmccaffery/numonic/blob/fix/issues/.github/ISSUE_TEMPLATE/feature-request.yml

**Comment by sjk07** [comment]
@dmccaffery These look great! 

one little thing is we don't have the code of conduct created yet is the uri in the templates a placeholder?
not a blocker

**Review by sjk07 — APPROVED** [review]

**Comment by dmccaffery** [comment]
placeholder; yes -- we should have one, but don't know what it should be yet :)

**Pull request merged**
